Algoritmo "concatenação"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2021
Var
// Seção de Declarações das variáveis 
     nome: caracter
     numero:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreval("digite o nome: ")
    leia(nome)
    escreval("digite o numero: ")
    leia(numero)

    escreval(nome, " : ", numero, 15)
Fimalgoritmo